### ISSUE TITLE
Python Exception，when i excute my program ,the exception was happend! 

### ISSUE THREAD

**Issue by Liangchengdeye** [swilly22/redis-graph#100]
Learn this web site: http://redisgraph.io/design/
When I execute: query6='GRAPH.QUERY IMDB'MATCH (a:actor) - [act] - > (m:movie {title: "Straight Outta Compton"}) RETURN m.title.
This code is in Python environment, redis_graph.query (query6).Pretty_print ().
The following errors will happen: Exception: **Row has incorrect number of values, (actual) 1! =3 (expected).
How to solve it, please?**
Pretty_print()??  how can i should it?

**Comment by swilly22** [comment]
Could you please provide the python code you're using?

**Comment by Liangchengdeye** [comment]
import redis
from redisgraph import Node, Edge, Graph
pool = redis.ConnectionPool(host='192.168.87.129', port=6379, db=0, password='root')
r = redis.Redis(connection_pool=pool)


query = '''
CREATE (aldis:actor {name: "Aldis Hodge", birth_year: 1986,age:20}),
(oshea:actor {name: "OShea Jackson", birth_year: 1991,age:21}),
(corey:actor {name: "Corey Hawkins", birth_year: 1988,age:23}),
(neil:actor {name: "Neil Brown", birth_year: 1980,age:30}),
(compton:movie {title: "Straight Outta Compton", genre: "Biography", votes: 127258, rating: 7.9, year: 2015}),
(neveregoback:movie {title: "Never Go Back", genre: "Action", votes: 15821, rating: 6.4, year: 2016}),
(aldis)-[act]->(neveregoback),
(aldis)-[act]->(compton),
(oshea)-[act]->(compton),
(corey)-[act]->(compton),
(neil)-[act]->(compton)
'''
redis_graph.query(query)
query4 = '''
MATCH (a:actor) return a
'''
s=redis_graph.query(query4).pretty_print()
query6 = '''
MATCH (a:actor)-[act]->(m:movie) where m.title="Straight Outta Compton"  return a.age,a.name,m.movie
'''
s=redis_graph.query(query6).pretty_print()

# query4 can excute,but query6 can'not excute , I don't why?

**Comment by Liangchengdeye** [comment]
sorry ! if i excute :query6='MATCH (a:actor)-[act]->(m:movie{title:"Straight Outta Compton"}) RETURN m.title,SUM(a.age),MAX(a.age), MIN(a.age),AVG(a.age)',It's also happend!
s=redis_graph.query(query6).pretty_print()
Exception: Row has incorrect number of values, (actual) 1!=5 (expected)

**Comment by swilly22** [comment]
You've forgotten to specify colons before 'act' within each relation you're creating,
in your case you're creating typeless relations, please use the query below to create your graph.

`'CREATE (aldis :actor {name: "Aldis Hodge", birth_year: 1986, age:20}), (oshea :actor {name: "OShea Jackson", birth_year: 1991, age:21}), (corey :actor {name: "Corey Hawkins", birth_year: 1988, age:23}), (neil :actor {name: "Neil Brown", birth_year: 1980, age:30}), (compton :movie {title: "Straight Outta Compton", genre: "Biography", votes: 127258, rating: 7.9, year: 2015}), (neveregoback :movie {title: "Never Go Back", genre: "Action", votes: 15821, rating: 6.4, year: 2016}), (aldis)-[:act]->(neveregoback), (aldis)-[:act]->(compton), (oshea)-[:act]->(compton), (corey)-[:act]->(compton), (neil)-[:act]->(compton)'`
