### ISSUE TITLE
Build Fails on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by jaladankisuresh** [swilly22/redis-graph#22]
Build Error while trying to build redis-graph with command: **cmake . && make module**

```bash
xxxxx@xxxxxxxx:/tmp/redis-4.0-rc3/utils/redis-graph$ cmake . && make module
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/redis-4.0-rc3/utils/redis-graph
[  0%] Building C object src/CMakeFiles/Llibgraph.dir/module.c.o
In file included from /tmp/redis-4.0-rc3/utils/redis-graph/src/graph/edge.h:4:0,
                 from /tmp/redis-4.0-rc3/utils/redis-graph/src/module.c:7:
/tmp/redis-4.0-rc3/utils/redis-graph/src/graph/node.h:9:16: warning: empty declaration with storage class specifier does not redeclare tag [enabled by default]
 typedef struct Edge;
                ^
/tmp/redis-4.0-rc3/utils/redis-graph/src/module.c: In function ‘_CreateGraphEntity’:
/tmp/redis-4.0-rc3/utils/redis-graph/src/module.c:56:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(int i = 0; i < propCount; i+=2) {
     ^
/tmp/redis-4.0-rc3/utils/redis-graph/src/module.c:56:5: note: use option -std=c99 or -std=gnu99 to compile your code
/tmp/redis-4.0-rc3/utils/redis-graph/src/module.c: In function ‘MGraph_AddEdge’:
/tmp/redis-4.0-rc3/utils/redis-graph/src/module.c:164:5: warning: passing argument 3 of ‘ConnectNode’ from incompatible pointer type [enabled by default]
     ConnectNode(srcNode, destNode, edge);
     ^
In file included from /tmp/redis-4.0-rc3/utils/redis-graph/src/graph/edge.h:4:0,
                 from /tmp/redis-4.0-rc3/utils/redis-graph/src/module.c:7:
/tmp/redis-4.0-rc3/utils/redis-graph/src/graph/node.h:31:6: note: expected ‘struct Edge *’ but argument is of type ‘struct Edge *’
 void ConnectNode(Node* src, Node* dest, struct Edge* e);
      ^
make[3]: *** [src/CMakeFiles/Llibgraph.dir/module.c.o] Error 1
make[2]: *** [src/CMakeFiles/Llibgraph.dir/all] Error 2
make[1]: *** [src/CMakeFiles/module.dir/rule] Error 2
make: *** [module] Error 2
```
FYI, i was able to successfully install rejson module on redis 4.0

Just wondering, How i could consume this module from Node.js / javascript. Any support?

**Comment by swilly22** [comment]
Hi jaladankisuresh,
Thank you for bringing this to my attention I'll try to fix this asap,

Currently there's a only a Python client for this module and a Java client development is underway,
In the meanwhile you can use a node.js Redis client to send the module's "raw" command,

\* new clients contributions would be great.

**Comment by jaladankisuresh** [comment]
Thank you for build this module, it seems very promising to me. I shall give it a try again, once the issue is resolved.

My Bash on Ubuntu on windows is on version 14.04.5
```bash
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
```

**Comment by swilly22** [comment]
Great, I'll look into it.

**Comment by swilly22** [comment]
@jaladankisuresh I've make some changes to the CMakeLists.txt file, please re-run `cmake .` from project root folder and `make clean module`.

Please make sure you've installed uuid-dev, `apt-get install uuid-dev`

**Comment by grv1207** [comment]
Hi,
I'm trying to build and after following above step now I'm getting;
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 2
>>> 'loadmodule "/<my directory>/redis-graph/src/libmodule.so"'
Bad directive or wrong number of arguments

**Comment by itamarhaber** [comment]
@grv1207 the unmaintained Windows fork of Redis does not support the new module's API.

**Comment by grv1207** [comment]
what should I do in this case? anyways I'm trying to build it on both mac and ubuntu

**Comment by itamarhaber** [comment]
@grv1207 you need to build and run Redis (and the module) on a platform that supports it. Ubuntu is the standard.

**Comment by grv1207** [comment]
I using Ubuntu and I have successfully build Redis on it, but not able to build Redis-graph on it : 
After installing apt-get install uuid-dev and 
then cmake ., 
when I try to run 
redis-server --loadmodule <my-path >/src/libmodule.so 

I get following error *** FATAL CONFIG FILE ERROR *** Reading the configuration file, at line 2 >>> 'loadmodule "/<my directory>/redis-graph/src/libmodule.so"' Bad directive or wrong number of arguments

**Comment by itamarhaber** [comment]
@grv1207 is your Redis server v4 or above? (currently RC3)

**Comment by swilly22** [comment]
@grv1207 
Are you using Redis config file to load the module, or are you using the --loadmodule flag?
Either way make sure you provide Redis with an absolute path to the module.

**Comment by grv1207** [comment]
So following configuration worked for me :
1. updated Redis server to v4 on Ubuntu
2. passed the complete path of redis-server when using --loadmodule flag.

Thanks guys for the help

**Comment by swilly22** [comment]
I've removed UUID, using snowflake to generate IDs.
