### ISSUE TITLE
how convert natural language to cypher queries?

### ISSUE THREAD

**Issue by colinsongf** [swilly22/redis-graph#27]
how to convert 1 to 2?

1.  Utterance: "Which actors played along side Nicolas Cage?"
---->?????
2.  cypher query: """MATCH (n:actor{name:"Nicolas Cage"})-[:act]->(m:movie)<-[:act]-(a:actor)
	RETURN a.name, m.title""";

**Comment by swilly22** [comment]
Hi,
I'm not sure I fully understand your question / issue,
Can you please elaborate?

**Comment by colinsongf** [comment]
how transfer natural language query into cypher query?
above is an example 
my query is Which actors played along side Nicolas Cage?", 
is there methods or program transfer to cypher query by computer tools

**Comment by swilly22** [comment]
I'm not sure there is at the moment, but It could be really interesting to come up with such a translator
