### ISSUE TITLE
HMSET + ADDEDGE is not working

### ISSUE THREAD

**Issue by fnchooft** [swilly22/redis-graph#29]
Hi Roi, cool module.

**One question:** if someone has modeled its entities with HMSET as you show in the example,  it would be really helpful to be able to use existing data-structures.

I was only able to get the graph working if i added the data, which i already have in a hash-map, via the CREATENODE-function.

The following snipplet is almost verbatim from the [design.md](https://github.com/swilly22/redis-graph/blob/master/docs/design.md)
```
127.0.0.1:6379[9]> HMSET A name a lastname Anton
OK
127.0.0.1:6379[9]> HMSET B name b lastname Bertha
OK
127.0.0.1:6379[9]> GRAPH.ADDEDGE relations A knows B
Error, missing node(s)
```

It might be helpful to have a REGISTERNODE-function if you must have a reference to the name of the HASH.

Something like:
```
GRAPH.REGISTERNODE relations person A 
```
where A would be the name of a HASH.
The ADDEDGE would become:
```
127.0.0.1:6379[9]> GRAPH.ADDEDGE relations A knows B
```

This works:
```
127.0.0.1:6379[9]> GRAPH.CREATENODE relations person name a lastname Anton
"226754816"
127.0.0.1:6379[9]> GRAPH.CREATENODE relations person name b lastname Bertha
"-1358692096"
127.0.0.1:6379[9]> GRAPH.ADDEDGE relations 226754816 knows -1358692096
"1841561856"
127.0.0.1:6379[9]> GRAPH.QUERY relations "MATCH (f:person)-[:knows]->(t:person) RETURN f.lastname,t.lastname"
1) "f.lastname,t.lastname\x00"
2) "Anton,Bertha"
3) "Query internal execution time: 0.075000 milliseconds"
```

Kind regards,

Fabian

**Comment by swilly22** [comment]
Hi Fabian,
Thank you for the feedback,

In the up and coming changes nodes / edges will no longer use Redis hashes to store their properties, this changes join a former change where entities id no longer map to Redis hash keys, so the only option would be to introduce a command similar to the one you've suggested (REGISTERNODE).

This could be done either within the module, or as part of a client library which reads a hash and create a new node from it, to keep the module commands list slim I would prefer a client side implementation.

Would love to hear your thoughts,
Thank you.

**Comment by fnchooft** [comment]
Ok - thanks for the info. The use-case was interesting since you could just use references to existing data-structures. But it is akin to other frameworks and you could still use node- and or edge-properties such as the tinkerpop-stack for instance.
Kind regards,

Fabian
