### ISSUE TITLE
Simple example does not work on provided Docker image

### ISSUE THREAD

**Issue by bengro** [swilly22/redis-graph#30]
**Context**
We are interested in trying out redis-graph and would like to run a simple example. We found your docker image and got the module up and running. We updated redis from rc2 to rc3.

**Problem**
We followed the simple example you provided in your tests:
```
hmset 'Roi' 'age' '32' 'name' 'Roi'
hmset 'Alon' 'age' '32' 'name' 'Alon'
hmset 'Omri' 'age' '31' 'name' 'Omri'

graph.ADDEDGE 'social' 'Roi' 'friend' 'Alon'
```

This errors with:
```
Error, missing node(s)
```

**Expectation**
I expect this simple example to run. I would like to know why it's failing, and where I'm going wrong. Documentation is missing a full example and could be more helpful.

**Comment by bengro** [comment]
Seems to be duplicate of https://github.com/swilly22/redis-graph/issues/29

**Comment by swilly22** [comment]
Hi @bengro,
Sorry I need to update the documentation, (hopefully this weekend)
Please see one of the demos available, on how to create nodes/edges using a python client, which basically calls GRAPH.ADDEDGE and GRAPH.CREATENODE.

So in the example above you would do:
GRAPH.CREATENODE <graph_name> <node_label> <properties>
Returns <node_id>

GRAPH.CREATENODE social person name Roi age 32
Replies with: <Roi's node_id>

GRAPH.CREATENODE social person name Alon age 32
Replies with: <Alon's node_id>

GRAPH.ADDEDGE <graph_name> <source_node_id> <relationship> <dest_node_id> <edge_props>
Returns <Edge_id>

GRAPH.ADDEDGE social <Roi's node_id> friend <Alon's node_id>
Replies with: <Edge_id>
