### ISSUE TITLE
Mass Insertion

### ISSUE THREAD

**Issue by ReganNZ** [swilly22/redis-graph#31]
Redis Graph looks really exciting and I'm keen to make use of it but I'm a bit stuck with the following:  

I currently import large amounts of data into Redis using the [mass insertion feature](https://redis.io/topics/mass-insert). Because with Redis Graph we need to get the node id after a GRAPH.CREATENODE command to able to run GRAPH.ADDEDGE I can't see how the mass insertion can work. 

Any ideas?

**Comment by swilly22** [comment]
Hi @ReganNZ,
I agree the problem lays within the need of both source node and the destination node ids.
I think a solution for this would be to allow both nodes and edge creation at once,
e.g. GRAPH.ADDEDGE <SOURCE_NODE LABEL + PROPERTIES> <EDGE TYPE> <DEST_NODE LABEL + PROPERTIES>

This way all entities (3) are created at once. the command will replay with the three ids just created.
What do you think?

**Comment by rmetzler** [comment]
Would there be a way to differentiate between
- create if node not exists
- error if node not exists
?

**Comment by swilly22** [comment]
As I see it, yes there will be a way to differentiate, either by introducing a new command or by including key words within the existing command e.g. GRAPH.ADDEDGE "SRC" <SOURCE_NODE LABEL + PROPERTIES> "EDGE" <EDGE TYPE + PROPERTIES>
"DEST" <DEST_NODE LABEL + PROPERTIES>

**Comment by ReganNZ** [comment]
Hi @swilly22, 
I'm not sure how this would work if you wanted add more than one edge using the same source node, you would still need the node id of the source node to create the second edge. 

I got some code working to get the redis-cli to suck in a massive txt file full of GRAPH.CREATENODE 
something like: cat tasks.txt | redis-cli > tasks-out.txt
I then parsed tasks-out.txt and matched node ids with ids from the SQL database (using the order in which they were inserted) then added GRAPH.ADDEDGE commands. It's a bit hacky/complicated but it worked and was still quite fast.

Maybe a way to get around this is to be able to specify our own node id on GRAPH.CREATENODE . One thing I noticed after importing is that I have millions of hashes keyed with the node id eg 471805832900903168. It makes the data rather opaque. If we could use our own node id say in the format graph:mylabel:myid it would work out well. I have very little understanding of how redis-graph works under the hood so feel free to say it won't work :-)

Thanks so much for your time.

**Comment by swilly22** [comment]
Hi @ReganNZ 
Sorry for my late response, at the beginning RedisGraph allowed user's to specify entities IDs,
at some point I've decided RedisGraph should act similarly to other databases in that matter, e.g. SQL databases users don't have control over inserted rows IDs for a number of reasons, one of them is ID conflict.

I'll try to come up with a better solution for mess inserts.
Thank you.

**Comment by swilly22** [comment]
@ReganNZ @rmetzler 
I've just pushed a beta version which supports open cypher CREATE clause,
You can use it to create both nodes and edges all at once, for instance:
GRAPH.QUERY social "CREATE (me:Person {name:Roi})-[:knows]->(a:Person {name:Amit), (me)-[:knows]->(s:Person {name:Shany})"

This will result in 3 new nodes and two new edges,
You can also combine MATCH and CREAT,

GRAPH.QUERY social "MATCH (me:Person {name:Roi})-[:knows]->(f:Person)
CREATE (j:Person {name:Junior})-[:knows]->(f)"

This will lookup the node which represents myself (Roi), find all of the people which I "know" of,
then it will create a single new node "Junior" and connect it with a "knows" edge (one foreach connection) to the people which I know.

**Comment by jimanvlad** [comment]
@swilly22 What about the MERGE function?

**Comment by swilly22** [comment]
Hi @jimanvlad 
Indeed supporting the MERGE function would be extremely useful, and I intend to add it in the near future, I haven't added it as part of the current effort (supporting CREAT) as MERGE requires a significant change within the execution plan runner.

**Comment by swilly22** [comment]
Large graphs can now be created in one go using the [CREATE](https://neo4j.com/docs/developer-manual/current/cypher/clauses/create/) query.
support for [MERGE](http://neo4j.com/docs/developer-manual/current/cypher/clauses/merge/) will be added later on.
