### ISSUE TITLE
Returning a node crashes redis-server

### ISSUE THREAD

**Issue by christyharagan** [swilly22/redis-graph#33]
If you run a query like this:

```
GRAPH.QUERY mygraph "MATCH (src:A)-[E]->(tgt:B) RETURN src"
```

Redis-server will crash with a log like this:

=== REDIS BUG REPORT START: Cut & paste starting from here ===
29410:M 18 Aug 11:41:12.716 # Redis 4.0.1 crashed by signal: 11
29410:M 18 Aug 11:41:12.716 # Crashed running the instuction at: 0x7fffda4d1b52
29410:M 18 Aug 11:41:12.716 # Accessing address: 0x0
29410:M 18 Aug 11:41:12.716 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
0   libsystem_c.dylib                   0x00007fffda4d1b52 strlen + 18

Backtrace:
0   redis-server                        0x0000000100ccc281 logStackTrace + 109
1   redis-server                        0x0000000100ccc60e sigsegvHandler + 236
2   libsystem_platform.dylib            0x00007fffda6aab3a _sigtramp + 26
3   ???                                 0x0000000000000020 0x0 + 32
4   libmodule.so                        0x0000000100e51062 ReturnClause_ExpandCollapsedNodes + 674
5   libmodule.so                        0x0000000100e4bf72 MGraph_Query + 306
6   redis-server                        0x0000000100cef243 RedisModuleCommandDispatcher + 97
7   redis-server                        0x0000000100c934d2 call + 215
8   redis-server                        0x0000000100c93c89 processCommand + 1300
9   redis-server                        0x0000000100c9ff71 processInputBuffer + 237
10  redis-server                        0x0000000100c8cfac aeProcessEvents + 543
11  redis-server                        0x0000000100c8d25b aeMain + 43
12  redis-server                        0x0000000100c9677d main + 1400
13  libdyld.dylib                       0x00007fffda49b235 start + 1
14  ???                                 0x0000000000000003 0x0 + 3

------ INFO OUTPUT ------
# Server
redis_version:4.0.1
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:f37081b32886670b
redis_mode:standalone
os:Darwin 16.7.0 x86_64
arch_bits:64
multiplexing_api:kqueue
atomicvar_api:atomic-builtin
gcc_version:4.2.1
process_id:29410
run_id:709917896ce392d931a8c6bbe947dc263a976c6e
tcp_port:6379
uptime_in_seconds:151
uptime_in_days:0
hz:10
lru_clock:9880648
executable:/code/github/redis-graph/redis-server
config_file:

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:1016912
used_memory_human:993.08K
used_memory_rss:2117632
used_memory_rss_human:2.02M
used_memory_peak:1016912
used_memory_peak_human:993.08K
used_memory_peak_perc:100.10%
used_memory_overhead:1013030
used_memory_startup:963248
used_memory_dataset:3882
used_memory_dataset_perc:7.23%
total_system_memory:8589934592
total_system_memory_human:8.00G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:2.08
mem_allocator:libc
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1503052721
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:1
total_commands_processed:2
instantaneous_ops_per_sec:0
total_net_input_bytes:243
total_net_output_bytes:152
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:e6a555d9ac0aee27fa8274919db88166e73b5ba1
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.08
used_cpu_user:0.04
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Commandstats

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=3,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=2 addr=127.0.0.1:55113 fd=8 name= age=147 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=graph.QUERY

------ CURRENT CLIENT INFO ------
id=2 addr=127.0.0.1:55113 fd=8 name= age=147 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=graph.QUERY
argv[0]: 'GRAPH.QUERY'
argv[1]: 'mygraph'
argv[2]: 'MATCH (src:A)-[E]->(tgt:B) RETURN src'
29410:M 18 Aug 11:41:12.717 # key 'mygraph' found in DB containing the following object:
29410:M 18 Aug 11:41:12.717 # Object type: 5
29410:M 18 Aug 11:41:12.717 # Object encoding: 0
29410:M 18 Aug 11:41:12.717 # Object refcount: 1

------ REGISTERS ------
29410:M 18 Aug 11:41:12.717 # 
RAX:0000000100cef8bf RBX:00007fff5ef76770
RCX:0000000000000000 RDX:0000000000000000
RDI:0000000000000000 RSI:0000000000000000
RBP:00007fff5ef76530 RSP:00007fff5ef76530
R8 :00000000000000c0 R9 :00007fd523c00000
R10:00000000ffff8000 R11:000000000000000a
R12:000000000000000f R13:000000005996c448
R14:00007fd52480bc00 R15:0000000100d39638
RIP:00007fffda4d1b52 EFL:0000000000010246
CS :000000000000002b FS:0000000000000000  GS:0000000000000000
29410:M 18 Aug 11:41:12.717 # (00007fff5ef7653f) -> 0000000000000001
29410:M 18 Aug 11:41:12.717 # (00007fff5ef7653e) -> 00007fff5ef765e0
29410:M 18 Aug 11:41:12.717 # (00007fff5ef7653d) -> 00007fff5ef76770
29410:M 18 Aug 11:41:12.717 # (00007fff5ef7653c) -> 00007fd500000000
29410:M 18 Aug 11:41:12.717 # (00007fff5ef7653b) -> 00000001da55642e
29410:M 18 Aug 11:41:12.717 # (00007fff5ef7653a) -> 0000000100cef8bf
29410:M 18 Aug 11:41:12.717 # (00007fff5ef76539) -> 00007fd523c0c9f0
29410:M 18 Aug 11:41:12.717 # (00007fff5ef76538) -> 00007fff5ef76770
29410:M 18 Aug 11:41:12.717 # (00007fff5ef76537) -> 00007fff5ef76770
29410:M 18 Aug 11:41:12.717 # (00007fff5ef76536) -> 0000000100cef8bf
29410:M 18 Aug 11:41:12.717 # (00007fff5ef76535) -> 0000000000000000
29410:M 18 Aug 11:41:12.717 # (00007fff5ef76534) -> 00007fff5ef76600
29410:M 18 Aug 11:41:12.717 # (00007fff5ef76533) -> 00007fff5ef76600
29410:M 18 Aug 11:41:12.717 # (00007fff5ef76532) -> 00007fff5ef76570
29410:M 18 Aug 11:41:12.717 # (00007fff5ef76531) -> 0000000100e51062
29410:M 18 Aug 11:41:12.717 # (00007fff5ef76530) -> 00007fff5ef76660

------ DUMPING CODE AROUND EIP ------
Symbol: strlen (base: 0x7fffda4d1b40)
Module: /usr/lib/system/libsystem_c.dylib (base 0x7fffda4d0000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=0x7fffda4d1b40 -D -b binary -m i386:x86-64 /tmp/dump.bin
------
29410:M 18 Aug 11:41:12.718 # dump of function (hexdump of 146 bytes):
554889e54889f94889fa4883e7f0660fefc0660f7407660fd7f04883e10f4883c8ff48d3e021c674170fbcc64829d74801f85dc36666662e0f1f8400000000004883c710660fefc0660f7407660fd7f085f674ecebd3909090909090909090904989f889f9f7d983e10f751f89f0b90010000025ff0f000029c14839d1480f47cac1e904754ab9100000004883fa1f770f89

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Comment by swilly22** [comment]
Thank you,
I'll look into it.
