### ISSUE TITLE
Make module for Ubuntu users

### ISSUE THREAD

**Issue by AemanMalik** [swilly22/redis-graph#35]
Hi,

Just a quick reminder that the quickstart should specify for ubuntu users to make module rather than make all. 

We were befuddled for a while until we figured that one out. 

Very small improvement to the documentation, should be easy to add (which also give a better impression for newbies) :)

Thx!

**Comment by swilly22** [comment]
Thank you @AemanMalik , noted.
I intend to a update the documentation soon.
