### ISSUE TITLE
Compiler errors on Debian 8 with GCC

### ISSUE THREAD

**Issue by 0x66656c6978** [swilly22/redis-graph#6]
Heya,

awesome project first of all!

I tried to compile it on a debian 8 64 bit with gcc 4.9 and cmake 3.0.2.
I got errors similar to this:
`error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode `.
The following line added to the CMakeLists.txt in the root directory made it compile just fine for my specific version of cmake:
`set (CMAKE_C_FLAGS "--std=gnu99 ${CMAKE_C_FLAGS}")`

AFAIK this is specific to gcc and cmake versions < 3.1. I am not very experienced with cmake and got most of the information from this stackoverflow thread: http://stackoverflow.com/questions/24840030/forcing-c99-in-cmake-to-use-for-loop-initial-declaration

Best regards!

**Comment by swilly22** [comment]
Hi,
Thanks for bring this up,
I'm not sure at the moment if I want to include this (as is) in the CMakeLists file,
So I'll leave this issue open for the time being.
