### ISSUE TITLE
Creating an edge between existing nodes

### ISSUE THREAD

**Issue by jsumakanth** [swilly22/redis-graph#61]
I have succeeded in creating multiple nodes and edges in the same pass using 
"CREATE (n1:node), (n2:node), (n1) - [:knows] -> (n2)"

Currently, Is there a way to create an edge between existing nodes? I have tried grouping "MATCH" and "CREATE" queries (They all returned back with syntax errors).

**Comment by swilly22** [comment]
It’s possible to connect existing nodes,
First locate the nodes you’ll like to connect and use the create clause to create a new edge.

Like so
Match (a:node), (b:node)
Where a.prop=value AND b.prop=value
Create (a)-[:knows]->(b)

**Comment by jsumakanth** [comment]
The example you provided gives me a syntax error for the use of ",". I have success trying to use one existing node though.

Here is the example I am trying on redis-cli

GRAPH.QUERY social "CREATE (:person {name: roi, age: 32, gender: male, status: married})"
GRAPH.QUERY social "CREATE (:person {name: dave, age: 23, gender: male, status: married})"

GRAPH.QUERY social "MATCH (a:person), (b:person) where a.name = roi AND b.name = dave CREATE (a) - [:knows] -> (b)"
(error) Syntax error at offset 18 near ','

A query with one existing node works as expected,
GRAPH.QUERY social "MATCH (a:person) where a.name = roi 
                                      CREATE (a) - [:knows] -> (:person {name: kyle, age: 43, gender: female, 
                                      status: married})"

Not sure if I am missing something in the syntax.

**Comment by swilly22** [comment]
My bad, this is a bug. the current parser doesn't allow to specify multiple patterns within the MATCH clause, I'll fix that ASAP,
Thank you!

**Comment by swilly22** [comment]
@jsumakanth I've extend the parser to support multiple patterns, please let me know if you're able to create an edge between two existing entities.
Thank you.

**Comment by jsumakanth** [comment]
That works like a charm! Thanks for the fix.
