### ISSUE TITLE
FastoRedis support redis-graph commands

### ISSUE THREAD

**Issue by topilski** [swilly22/redis-graph#64]
Hi, i want add redis-graph commands into FastoRedis, can you explain which command should be handle?

**Comment by swilly22** [comment]
I think all commands (3) should be added:
1.graph.DELETE
2.graph.QUERY 
3.graph.EXPLAIN

**Comment by topilski** [comment]
Thank you @swilly22 , do you have some examples to test all this commands. Also want ask you which keys types should appear after execution of this commands?

**Comment by swilly22** [comment]
The key types are custom (not Redis native data-types)
Please see demo folder for usage of both GRAPH.QUERY and GRAPH.EXPLAIN

**Comment by topilski** [comment]
Hi @swilly22 , i implemented redis-graph commands initialization now worked in same way like in redis-cli, i also want ask about graph drawing, FastoRedis is gui application unlike redis-cli, may be will be useful have some ability to drawing graphs directly in application what you think? any suggestions, may be some other functionality? thank you for help!

**Comment by topilski** [comment]
Also i can view custom keys type, but i need some knowledge hot to view this keys.

**Comment by swilly22** [comment]
Graph visualisation would be nice, but you'll need to figure out the graph structure from the user query and the response, which isn't trivial, as responses are tabular. also there are times where the result of a query isn't a graph e.g. aggregation query.

I think it would be nice to have auto complete/correction for query composing.

Regarding RedisGraph custom keys, they hold a trie data structure, you can see its implementation within the source code.

**Comment by topilski** [comment]
Hi @swilly22 , thank you for response i will investigate your suggestions.
