### ISSUE TITLE
GRAPH.QUERY IMDB  ""    error

### ISSUE THREAD

**Issue by zhenruyan** [swilly22/redis-graph#66]
=== REDIS BUG REPORT START: Cut & paste starting from here ===
28969:M 10 Nov 11:08:39.079 # Redis 4.0.2 crashed by signal: 11
28969:M 10 Nov 11:08:39.079 # Crashed running the instuction at: 0x7fc19a1e02d4
28969:M 10 Nov 11:08:39.079 # Accessing address: (nil)
28969:M 10 Nov 11:08:39.079 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
./graoh.so(_ExecutionPlan_OptimizeEntryPoints+0x24)[0x7fc19a1e02d4]

**Comment by swilly22** [comment]
Hi @zhenruyan 
What was the query you were trying to run?
GRAPH.QUERY IMDB "" ? (as in empty string)

**Comment by zhenruyan** [comment]
When the input the wrong grammar or is an empty string
Leads to a redis interrupt directly

**Comment by zhenruyan** [comment]
![_deepin-terminal_20171111101505](https://user-images.githubusercontent.com/9253251/32685327-dc46b1c0-c6c9-11e7-84c9-f646a69d0310.gif)

**Comment by zhenruyan** [comment]
`Redis server v=4.0.2 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=916d23d225484bee

Linux free 4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19) x86_64 GNU/Linux

**Comment by swilly22** [comment]
Starting to validate produced AST.
