### ISSUE TITLE
certain edge queries crash redis 

### ISSUE THREAD

**Issue by RMKD** [swilly22/redis-graph#67]
From redis-cli, matching against edge types works fine when returning nodes:
`GRAPH.QUERY testgraph "MATCH (p)-[r:connects]->(q) RETURN p,q"`

so does: 
`GRAPH.QUERY testgraph "MATCH (p)-[r:connects]->(q) RETURN p,r,q"`
(though the edge does not appear to be in the response)

but this crashes the redis server:
`GRAPH.QUERY testgraph "MATCH (p)-[r:connects]->(q) RETURN r"`

```
=== REDIS BUG REPORT START: Cut & paste starting from here ===
7182:M 10 Nov 14:03:05.082 # Redis 4.0.2 crashed by signal: 11
7182:M 10 Nov 14:03:05.082 # Crashed running the instuction at: 0x7fc5617feb1d
7182:M 10 Nov 14:03:05.082 # Accessing address: 0x562bfa70afe7
7182:M 10 Nov 14:03:05.082 # Failed assertion: <no assertion failed> (<no file>:0)


------ STACK TRACE ------
EIP:
/usr/lib/libc.so.6(+0x157b1d)[0x7fc5617feb1d]

Backtrace:
redis-server *:6379(logStackTrace+0x5c)[0x562bf90fda0c]
redis-server *:6379(sigsegvHandler+0xb4)[0x562bf90fe1b4]
/usr/lib/libpthread.so.0(+0x11da0)[0x7fc561a6fda0]
/usr/lib/libc.so.6(+0x157b1d)[0x7fc5617feb1d]
redis-server *:6379(sdsnewlen+0xc9)[0x562bf90bfdb9]
redis-server *:6379(+0x41369)[0x562bf90ca369]
redis-server *:6379(addReplyBulkCBuffer+0x28)[0x562bf90cb678]
redis-server *:6379(RM_ReplyWithStringBuffer+0x1c)[0x562bf9127aac]
<path>/redis-graph/src/redisgraph.so(ResultSet_Replay+0x227)[0x7fc55f5eac17]

------ INFO OUTPUT ------

```
querying a nonexistent edge label has the same effect: 
`GRAPH.QUERY testgraph "MATCH (p)-[r:notanedgelabel]->(q) RETURN p,q"`

**Comment by swilly22** [comment]
Hi @RMKD 
Thank you for bringing this to my attention,
I'll look into it ASAP.

**Comment by swilly22** [comment]
I couldn't reproduce,
Checked against latest version #68 and I'm able to retrieve: both nodes and edges or anyone of them individually.
