### ISSUE TITLE
Issues on Raspberry PI  -- first graph command causes redis to freeze

### ISSUE THREAD

**Issue by glenn-edgar** [swilly22/redis-graph#82]
1. The graph module on the raspberry pi successfully.
2. The graph module loaded successfully on startup.
3. Issuing the redis-cli command
GRAPH.QUERY social "CREATE (:person {name: 'roi', age: 32, gender: 'male', status: 'married'})"
causes the redis server to freeze.  
    A. No message on console
    B. No reply on redis-cli console.
    C. Any attempt to connect with another redis-cli module is refused
4.  Supporting information
   A.  redis server is redis-4.0.6  operating in 32 bit mode
   B.  The modules redis-search and redis-json load and operate correctly

Be happy to supply additional info

**Comment by swilly22** [comment]
Hi @glenn-edgar ,
I've never tried RedisGraph on the PI,
I'll get my hands on one and investigate (unless there's an emulator I can use).

Thank you for bringing this to my attention.

**Comment by dvirsky** [comment]
This is probably mostly due to TrieMap's unaligned access. It needs a bit of rewrite to work on ARM
