### ISSUE TITLE
MODULE LOAD command have been deprecated

### ISSUE THREAD

**Issue by saumya-singh** [swilly22/redis-graph#88]
In **index.md** the MODULE LOAD command mentioned have now been deprecated, **Loading the module to Redis** section could be updated.

**Comment by swilly22** [comment]
@saumya-singh Can you please refer me to Redis documentation saying the module load command is deprecated?

**Comment by saumya-singh** [comment]
I'm sorry.. the command has not been deprecated , the link provided for MODULE LOAD is not available anymore.
Link to [Redis Modules] (https://redis.io/topics/modules-intro) contains info on 'Loading modules'.
