### ISSUE TITLE
Local results for movie example don't match docs

### ISSUE THREAD

**Issue by oubiwann** [swilly22/redis-graph#92]
When trying to get more context for issue #91 (crashing Redis), I looked at the example provided on the docs page here:
* http://redisgraph.io/design/

I created the `IMDB` graph:

```
127.0.0.1:6379> graph.QUERY IMDB 'CREATE (aldis:actor {name: "Aldis Hodge", birth_year: 1986}),(oshea:actor {name: "OShea Jackson", birth_year: 1991}),(corey:actor {name: "Corey Hawkins", birth_year: 1988}),(neil:actor {name: "Neil Brown", birthyear: 1980}),(compton:movie {title: "Straight Outta Compton", genre: "Biography", votes: 127258, rating: 7.9, year: 2015}),(neveregoback:movie {title: "Never Go Back", genre: "Action", votes: 15821, rating: 6.4, year: 2016}),(aldis)-[act]->(neveregoback),(aldis)-[act]->(compton),(oshea)-[act]->(compton),(corey)-[act]->(compton),(neil)-[act]->(compton)'
```
with the following result:
```
1) 1) ""
2) 1) Labels added: 6
   2) Nodes created: 6
   3) Properties set: 18
   4) Relationships created: 1
   5) "Query internal execution time: 0.125000 milliseconds"
```
That doesn't look right; only 1 relation? I count 5 ...

Similarly, I see the following differences with what's presented on that page with the other two queries.

Query:

```
127.0.0.1:6379> GRAPH.QUERY IMDB "MATCH (a:actor)-[act]->(m:movie {title:\"Straight Outta Compton\"}) RETURN m.title, SUM(a.age), MAX(a.age), MIN(a.age), AVG(a.age)"
```
Result:
```
1) 1) "m.title,SUM(a.age),MAX(a.age),MIN(a.age),AVG(a.age)\x00"
2) 1) "Query internal execution time: 0.101000 milliseconds"
```
Query:
```
127.0.0.1:6379> GRAPH.QUERY IMDB "MATCH (actor)-[act]->(movie) RETURN actor.name, COUNT(movie.title) AS movies_count ORDER BY movies_count DESC"
```
Result:
```
1) 1) "actor.name,movies_count\x00"
   2) "Aldis Hodge,1.000000"
2) 1) "Query internal execution time: 0.112000 milliseconds"
```

**Comment by oubiwann** [comment]
Hrm, no; it all looks correct :-/

**Comment by swilly22** [comment]
@oubiwann When forming connection you need to use the following pattern:
(s:Label)-[e:Relation]->(d:Label)
Where s, e and d are aliases given to the entities and what follows ':' is the label/relation
In the example you've posted, 'act' is an alias/variable, (you've not specified the type of relation which you're not obligated to do so)

I think once 'act' gets bounded to an actual edge (first insertion) it is not recreated (might be a bug)
I need to further investigate this.

For now I'll suggest specifying edge label:

`graph.QUERY IMDB 'CREATE (aldis:actor {name: "Aldis Hodge", birth_year: 1986}), (oshea:actor {name: "OShea Jackson", birth_year: 1991}), (corey:actor {name: "Corey Hawkins", birth_year: 1988}), (neil:actor {name: "Neil Brown", birthyear: 1980}), (compton:movie {title: "Straight Outta Compton", genre: "Biography", votes: 127258, rating: 7.9, year: 2015}), (neveregoback:movie {title: "Never Go Back", genre: "Action", votes: 15821, rating: 6.4, year: 2016}), (aldis)-[:act]->(neveregoback), (aldis)-[:act]->(compton), (oshea)-[:act]->(compton), (corey)-[:act]->(compton), (neil)-[:act]->(compton)'`

**Comment by swilly22** [comment]
Documentation been updated.

**Comment by oubiwann** [comment]
I was wondering about that ... wasn't sure if the relations without the colon were a dialectical variation -- thanks for clarifying! (should have tested that ...)

The new create query you provided works like a charm: the two match queries now return the expected results (incidentally, for those both `:act` and `act` work).

I did notice something odd while testing this: when restarting Redis with clients still connected, Redis would crash (but with no debug output).

**Comment by oubiwann** [comment]
Checked the docs, looks good :-)

Thanks!
